package org.vasanth.jeeranker.dto;

public enum SearchOperator {
  CONTAINS,
  DOES_NOT_CONTAIN,
  EQUAL,
  NOT_EQUAL,
  BEGINS_WITH,
  DOES_NOT_BEGIN_WITH,
  ENDS_WITH,
  DOES_NOT_END_WITH,
  NULL,
  NOT_NULL,
  GREATER_THAN,
  GREATER_THAN_EQUAL,
  LESS_THAN,
  LESS_THAN_EQUAL,
  ANY,
  ALL;
}
