CREATE TABLE CUTOFF_RANKS
(
    ID            INT PRIMARY KEY AUTO_INCREMENT,
    INSTITUTE     VARCHAR(225),
    PROGRAM       VARCHAR(225),
    QUOTA         VARCHAR(225),
    SEAT_TYPE     VARCHAR(225),
    GENDER        VARCHAR(225),
    OPENING_RANK  VARCHAR(225),
    CLOSING_RANK  VARCHAR(225),
    ACADEMIC_YEAR INT,
    ROUND         INT,
    TYPE          VARCHAR(225)
);

INSERT INTO
    CUTOFF_RANKS(INSTITUTE, PROGRAM, QUOTA, SEAT_TYPE, GENDER, OPENING_RANK, CLOSING_RANK, ACADEMIC_YEAR, ROUND, TYPE)
    SELECT * FROM CSVREAD('src/main/resources/2023.csv');

INSERT INTO
    CUTOFF_RANKS(INSTITUTE, PROGRAM, QUOTA, SEAT_TYPE, GENDER, OPENING_RANK, CLOSING_RANK, ACADEMIC_YEAR, ROUND, TYPE)
SELECT * FROM CSVREAD('src/main/resources/2022.csv')